### ISSUE TITLE
Advertise key thumbprints

### ISSUE THREAD

**Issue by sarroutbi** [latchset/tang-operator#2]
In order to ease key management in tang servers deploy via tang-operators, a new feature should be added to provide active and hidden key thumbprints in status field via K8S native API.

An example of the provided data could be as follows:

```
apiVersion: tangoperator.openshift.io/v1
kind: TangServer
metadata:
  name: exampleServer01
spec:
  port: 7500
  replicas: 3
  hiddenKeys:
  - sha1: shortthumbprint
status:
  running: 3
  ready: 3
  url: http://tang.cluster.fqdn:7500
  activeKeys:
  - sha1: NEWshorthumbprint
    sha256: NEWlongthumbprintismuchlonger
    generated: 2021-10-01T16:32:18Z
  hiddenKeys:
  - sha1: shorthumbprint
    sha256: longthumbprintismuchlonger
    generated: 2021-09-01T15:00:32Z
    hidden: 2021-10-01T16:32:18Z
```
