### ISSUE TITLE
Limit statticcheck Github action to .go files

### ISSUE THREAD

**Issue by sarroutbi** [latchset/tang-operator#79]
statticcheck Github action execution should be limited to .go files. More information on how to do this on:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

Check the `paths` option, as it can be used to specify wildcards:

```
on:
  push:
    paths:
      - '**.go'
```
